# Base image

FROM python:3.12-slim

WORKDIR /app

# Copy client code
COPY ../client /app

# Set HOST and PORT from environment (for Docker Compose)
ENV HOST=server
ENV PORT=9000

# Run client
CMD ["python", "client.py"]